replicaCount: 1

image:
  repository: ramon1743/simple-server
  pullPolicy: IfNotPresent
  tag: "0.0.1"

imagePullSecrets: []

service:
  type: NodePort
  port: 80

containerPort: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
